# Token reminder: github > settings > developer > > tokens > (re)generate, no scope > copy on clipoard
# On travis repo settings: assign the clipboard to GH_REPO_TOKEN
language: sh

# latest distribution
# https://docs.travis-ci.com/user/reference/overview/
dist: focal

# just master branch (verify branch name)
branches:
  only:
    - main

# Install dependencies
addons:
  apt:
    packages:
      - zsh

# environment must be defined
# one build will be triggered for each line in the env array.
env:
  - TRAVISENVIRONMENT=yes

# script to execute
script:
  - ./test/clientTests.sh
  - ./test/sbTests.sh

